# Generated by Django 2.1.2 on 2018-10-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='app_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='site_applied_from',
        ),
    ]
