# Generated by Django 2.0.4 on 2018-10-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181014_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_notes', to='api.Company'),
        ),
    ]
